### ISSUE TITLE
Move repo to openstreetmap/ organization

### ISSUE THREAD

**Issue by Komzpa** [openstreetmap/owg-website#21]
It would be good to have OpenStreetMap Foundation Operations Working Group reports not under personal account, but at organization.

**Comment by gravitystorm** [comment]
We've been in the process of upgrading this site to cover more of what OWG does - including publishing our policies and meeting summaries, in additions to the logs. As part of that we're moving the site to a more appropriate domain, https://operations.osmfoundation.org 

I now need to change the name of the repo, and so I'm considering moving it to the osmf organisation at https://github.com/osmfoundation (but I don't have access yet). @Komzpa what are your thoughts on osmfoundation vs openstreetmap github organisations?

**Comment by Komzpa** [comment]
I don't really see a good reason why it should be separate from https://github.com/openstreetmap/operations - both are in fact OWG issue trackers / operations logs.

**Comment by tomhughes** [comment]
Well the obvious reason is that both already exist and there's no way to merge git repositories... Now it's true the other one had very few commits so we could just overwrite it and keep the tickets.

**Comment by Komzpa** [comment]
A minute of googling says there is a key in git to merge unrelated repositories/histories, if it's really required: http://stackoverflow.com/a/10548919/1982959
But probably not really required for a single README file.

**Comment by gravitystorm** [comment]
I've moved the repository to https://github.com/openstreetmap/owg-website/  . I've kept it separate from the OWG task tracker since I don't think there's great advantage in having website issues (e.g. changing bootstrap themes) mixed in with the higher-level issues of a task tracker. Or to look at it in reverse, it would be strange to open an issue "buy new servers" in the issue tracker for our website!
